---
sudo: required
services:
  - docker
branches:
  only:
    - master

script:
- docker build -f Ubuntu .
- docker build -f Debian .
- docker build -f Centos .
- docker build -f Fedora .
- docker build -f OpenSuse .
