---
sudo: required
services:
  - docker
branches:
  only:
    - master

script:
- docker build -t scottmiller171/ubuntu-ansible:latest -f Ubuntu .
- docker build -t scottmiller171/debian-ansible:latest -f Debian .
- docker build -t scottmiller171/centos-ansible:latest -f Centos .
- docker build -t scottmiller171/opensuse-ansible:latest -f OpenSuse .

after_script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push scottmiller171/ubuntu-ansible:latest
- docker push scottmiller171/debian-ansible:latest
- docker push scottmiller171/centos-ansible:latest
- docker push scottmiller171/opensuse-ansible:latest
