---
sudo: required
services:
  - docker
branches:
  only:
    - master

script:
- docker build -t scottmiller171/ubuntu-ansible:latest -f Ubuntu .
- docker build -t scottmiller171/debian-ansible:latest -f Debian .
- docker build -t scottmiller171/centos-ansible:latest -f Centos .
- docker build -t scottmiller171/opensuse-ansible:latest -f OpenSuse .

deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh
  on:
    branch: master
